### ISSUE TITLE
async subscribe_invoices() problem

### ISSUE THREAD

**Issue by avantgarden** [kornpow/lnd-grpc-client#2]
Hello,

seems there is a problem with async subscribe_invoices(). I'm using Async code from README... Does it work for you?

Listening for invoices...
/home/jozef/dev/gallery/cloudinary-flask-main/selfie/lightning_part.py:46: RuntimeWarning: coroutine 'AsyncLNDClient.subscribe_invoices' was never awaited
  async for invoice in async_lnd.subscribe_invoices():
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from selfie import app
  File "/home/jozef/dev/gallery/cloudinary-flask-main/selfie/__init__.py", line 17, in <module>
    from selfie import routes
  File "/home/jozef/dev/gallery/cloudinary-flask-main/selfie/routes.py", line 7, in <module>
    from selfie.lightning_part import lnd
  File "/home/jozef/dev/gallery/cloudinary-flask-main/selfie/lightning_part.py", line 61, in <module>
    asyncio.run(run())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/jozef/dev/gallery/cloudinary-flask-main/selfie/lightning_part.py", line 58, in run
    await asyncio.gather(*coros)
  File "/home/jozef/dev/gallery/cloudinary-flask-main/selfie/lightning_part.py", line 46, in subscribe_invoices
    async for invoice in async_lnd.subscribe_invoices():
TypeError: 'async for' requires an object with __aiter__ method, got coroutine

**Comment by kornpow** [comment]
let me check this out, I dont use the async stuff that often so maybe there is an issue in the library or the example code
